DAOS-11032 build: Update SPDK to v22.01.2 maintenance release
daos-stack/spdk pull request #52
Opened 2022-11-24 15:29 UTC by tanabarr

Update SPDK packaging to version 22.01.2 to pick up VMD-hotplug related changes.

Signed-off-by: Tom Nabarro <tom.nabarro@intel.com>

2022-11-24 17:33 UTC, brianjmurrell requested changes
Don't forget to update https://github.com/daos-stack/spdk/blob/a3a14f5ad6cc1744f09a4723b8bdffadd0b2e7d0/debian/control#L7

2022-11-25 11:26 UTC, tanabarr commented
> Don't forget to update
> 
> https://github.com/daos-stack/spdk/blob/a3a14f5ad6cc1744f09a4723b8bdffadd0b2e7d0/debian/control#L7

Should we also update L34 from `libspdk20` to `libspdk22`?

2022-11-25 16:11 UTC, brianjmurrell commented
> Should we also update L34 from `libspdk20` to `libspdk22`?

Hrm.  This really never should have been `libspdk20`.  It should have been `libspdk2`.  But indeed, now it should be `libspdk3` as the major version of `libspdk.so` is 3 now.  It was 2 before.

Hopefully our `libspdk20` package is long gone by the time they get their major version up to 20.

2022-11-30 16:29 UTC, brianjmurrell requested changes
dpdk PR needs to land first.

2022-11-30 16:29 UTC, brianjmurrell commented on Jenkinsfile
> +@Library(value="pipeline-lib@bmurrell/stop-testing-with-2.0") _
This needs to be removed before it can land.

2022-11-30 21:32 UTC, jolivier23 approved these changes

2022-12-01 03:06 UTC, brianjmurrell approved these changes

2022-12-01 18:59 UTC, brianjmurrell commented
> Hrm. This really never should have been `libspdk20`. It should have been `libspdk2`. But indeed, now it should be `libspdk3` as the major version of `libspdk.so` is 3 now. It was 2 before.
> 
> Hopefully our `libspdk20` package is long gone by the time they get their major version up to 20.

This still seems to be outstanding.

2022-12-01 19:00 UTC, brianjmurrell requested changes
libspdk20 -> libspdk3 for debian packaging still needs doing.

2022-12-01 20:28 UTC, tanabarr commented
> > Hrm. This really never should have been `libspdk20`. It should have been `libspdk2`. But indeed, now it should be `libspdk3` as the major version of `libspdk.so` is 3 now. It was 2 before.
> > Hopefully our `libspdk20` package is long gone by the time they get their major version up to 20.
> 
> This still seems to be outstanding.

as described on Skype I tried this but there were multiple errors so I thought I would update that in a separate PR given its tangential to the purpose of this PR. does that sound okay @brianjmurrell . if you look at the previous builds you can see the failures

2022-12-05 21:02 UTC, merged